# Generated by Django 2.2.6 on 2019-11-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('curd', '0002_auto_20191101_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curd.PermissionGroup'),
        ),
    ]
