# Generated by Django 2.2.6 on 2019-11-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('curd', '0004_remove_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curd.PermissionGroup'),
        ),
    ]
