# Generated by Django 2.2.3 on 2019-09-25 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='title',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Form_login.Classes'),
        ),
    ]
