# Generated by Django 2.2.7 on 2019-11-13 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0002_auto_20191113_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
