# Generated by Django 2.2.6 on 2019-10-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
