# Generated by Django 2.2.3 on 2019-09-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190914_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tea',
            new_name='theclass',
        ),
    ]
