# Generated by Django 2.2.3 on 2019-09-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190914_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(1, 'man'), (2, 'womam')])),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='theclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Classes'),
        ),
    ]
