# Generated by Django 2.2.3 on 2019-09-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190917_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='U2U',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Orm',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='u2u',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='girls', to='blog.UserInfo'),
        ),
        migrations.AddField(
            model_name='u2u',
            name='g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boys', to='blog.UserInfo'),
        ),
    ]
