# Generated by Django 2.2.3 on 2019-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_auto_20190827_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='student',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher', models.CharField(max_length=16)),
                ('tea', models.ForeignKey(on_delete=None, to='blog.Class')),
            ],
        ),
    ]
