# Generated by Django 2.2.3 on 2019-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_userinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=29),
        ),
    ]
