# Generated by Django 2.2.3 on 2020-05-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190920_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='theclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Classes'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
        migrations.AlterUniqueTogether(
            name='u2u',
            unique_together={('b', 'g')},
        ),
    ]
