# Generated by Django 2.2.3 on 2019-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
