# Generated by Django 2.2.6 on 2019-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0002_auto_20191107_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(auto_created=True),
        ),
    ]
