# Generated by Django 2.2.3 on 2019-09-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
                ('gender', models.IntegerField(choices=[('男', 1), ('女', 2)])),
                ('m', models.ManyToManyField(to='login.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                (
                'reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.Comment')),
            ],
        ),
    ]
